apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-backend
  namespace: cp2
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: cp2acr.azurecr.io/cp2-repo/mysql:cp2
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/mnt/data/"
          name: pvc-volume
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_password
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-mysql
