apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: cp2
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
