- name: Instalación de Podman en la máquina Linux
  hosts: linux_vm
  become: true
  tasks:
   - name: Instalar Podman
     ansible.builtin.apt:
       name: podman
       update_cache: true

- name: Disponibilizar imagen de Nginx en el ACR
  hosts: linux_vm
  vars_files: secrets.yaml
  tasks:
    - name: Logear Podman en el ACR
      containers.podman.podman_login:
        registry: cp2acr.azurecr.io
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
    
    - name: Descargar imagen de Nginx
      containers.podman.podman_image:
        name: docker.io/library/nginx

    - name: Tagear imagen de Nginx
      containers.podman.podman_tag:
        image: docker.io/library/nginx:latest
        target_names: cp2acr.azurecr.io/cp2-repo/nginx:latest

    - name: Subir imagen de Nginx al ACR
      containers.podman.podman_image:
        name: cp2acr.azurecr.io/cp2-repo/nginx:latest
        push: true

    - name: Eliminar imagenes de la maquina
      containers.podman.podman_image:
        name: b52e0b094bc0
        state: absent
        force: true

- name: Desplegar el contenedor Podman de Nginx
  hosts: linux_vm
  tasks:
    - name: Descargar imagen del ACR
      containers.podman.podman_image:
        name: cp2acr.azurecr.io/cp2-repo/nginx:latest

    - name: Levantar contenedor
      containers.podman.podman_container:
        name: nginx-container
        image: cp2acr.azurecr.io/cp2-repo/nginx:latest
        publish: 8080:80
